spring:
  apllication:
    name: config-Default
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registery: true
    register-with-eureka: true
    server-url:
      default-zone: http://localhost:8761/eureka
